-- database/migrations/V000__tablespaces_usuarios.sql
-- V000: tablespaces y usuarios aislados para los 5 entornos de negocio.
-- Se ejecuta una vez como SYSTEM en FREEPDB1.
-- La password real se inyecta en ejecucion (__APP_PWD__ -> $APP_USER_PWD).
-- Ver scripts/deployment/env/08-ejecutar-migraciones.sh
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

-- Limpieza idempotente para reejecuciones del laboratorio (ignora si no existen).
BEGIN
  FOR r IN (SELECT 'ACADEMIA' u FROM DUAL UNION ALL SELECT 'CLINICA' FROM DUAL UNION ALL SELECT 'RETAIL' FROM DUAL UNION ALL SELECT 'LOGISTICA' FROM DUAL UNION ALL SELECT 'FINTECH' FROM DUAL) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP USER ' || r.u || ' CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
  FOR r IN (SELECT 'TS_ACADEMIA' t FROM DUAL UNION ALL SELECT 'TS_CLINICA' FROM DUAL UNION ALL SELECT 'TS_RETAIL' FROM DUAL UNION ALL SELECT 'TS_LOGISTICA' FROM DUAL UNION ALL SELECT 'TS_FINTECH' FROM DUAL) LOOP
    BEGIN EXECUTE IMMEDIATE 'DROP TABLESPACE ' || r.t || ' INCLUDING CONTENTS AND DATAFILES'; EXCEPTION WHEN OTHERS THEN NULL; END;
  END LOOP;
END;
/

CREATE TABLESPACE TS_ACADEMIA DATAFILE '/opt/oracle/oradata/FREE/TS_ACADEMIA01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
CREATE TABLESPACE TS_CLINICA DATAFILE '/opt/oracle/oradata/FREE/TS_CLINICA01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
CREATE TABLESPACE TS_RETAIL DATAFILE '/opt/oracle/oradata/FREE/TS_RETAIL01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
CREATE TABLESPACE TS_LOGISTICA DATAFILE '/opt/oracle/oradata/FREE/TS_LOGISTICA01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;
CREATE TABLESPACE TS_FINTECH DATAFILE '/opt/oracle/oradata/FREE/TS_FINTECH01.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE USER ACADEMIA IDENTIFIED BY "__APP_PWD__" DEFAULT TABLESPACE TS_ACADEMIA QUOTA UNLIMITED ON TS_ACADEMIA;
CREATE USER CLINICA IDENTIFIED BY "__APP_PWD__" DEFAULT TABLESPACE TS_CLINICA QUOTA UNLIMITED ON TS_CLINICA;
CREATE USER RETAIL IDENTIFIED BY "__APP_PWD__" DEFAULT TABLESPACE TS_RETAIL QUOTA UNLIMITED ON TS_RETAIL;
CREATE USER LOGISTICA IDENTIFIED BY "__APP_PWD__" DEFAULT TABLESPACE TS_LOGISTICA QUOTA UNLIMITED ON TS_LOGISTICA;
CREATE USER FINTECH IDENTIFIED BY "__APP_PWD__" DEFAULT TABLESPACE TS_FINTECH QUOTA UNLIMITED ON TS_FINTECH;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO ACADEMIA;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO CLINICA;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO RETAIL;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO LOGISTICA;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO FINTECH;

EXIT
